### ISSUE TITLE
TempAR plugin issue

### ISSUE THREAD

**Issue by Altheon1994** [ONElua/AdrenalineBubbleManager#110]
- PSVITA model: [PCH-1104]
- Version of firmware: [3.60 Henkaku Enso]
- Version of ABM: [5.26]
- Version of Adrenaline: [6.61]

## After installing ABM and creating some bubbles

Obtained result: [Everything’s working fine save for accessing TempAR’s menu]

## Explain the issue

- [TempAR is pretty much like CWcheats in practice, except you can open it while in-game. The issue is TempAR can’t be triggered (R+Home button) if you launch a psp game using an ABM created bubble. Whereas it works if you launch a game directly from Adrenaline]

## Extra info

- [Tried outsourcing to reddit after trying to fiddle with the home function settings. They agree this is a unique issue and should be sent here.]
- [using sd2vita as ux0: and mmc as uma0:]

**Comment by ONElua** [comment]
Try np9660 driver

**Comment by naaiil** [comment]
i have same issue. already try change driver to np9660 but still not solved the issue

**Comment by ONElua** [comment]
The problem is adrenaline_booter (Hopefully there will be a fix soon)
Try trying the CW Cheat plugin

**Comment by ONElua** [comment]
From Lman:
It works without issue using this version of tempar plugin:
https://www.brewology.com/downloads/download.php?id=13092&mcid=1

Do reset booter settings from Adrenaline Menu->Booter tab->Reset
Booter Settings,
and try to change Tempar's open menu buttons, by using other
combination without the home button (PS)
since the PS button in Booter has been changed to open Menu or Goto LiveArea.

**Comment by Altheon1994** [comment]
Alright, I'll test these options out. Thanks for the response!
