### ISSUE TITLE
Could not load adrenaline_kernel

### ISSUE THREAD

**Issue by SaiyanFantasyX** [ONElua/AdrenalineBubbleManager#124]
- PSVITA model: [PCH 2006]
- Version of firmware: [3.68]
- Version of ABM: [6.12]
- Version of Adrenaline: [6.61 9]

## After installing ABM and creating some bubbles
After setting up sd2vita I could not load bubbles anymore. Tells me it couldn't load the plugin. 
Using sd2vita as ux0.
My config file:
This file is used as an alternative if ux0:tai/config.txt is not found.
# For users plugins, you must refresh taiHEN from HENkaku Settings for
# changes to take place.
# For kernel plugins, you must reboot for changes to take place.
*KERNEL
ur0:tai/nonpdrm.skprx
ur0:tai/storagemgr.skprx
ux0:app/PSPEMUCFW/sce_module/adrenaline_kernel.skprx
ur0:tai/LOLIcon.skprx
#ux0:tai/kuio.skprx
#ux0:tai/vsh.suprx
ux0:tai/ioplus.skprx
ur0:tai/reF00D.skprx
# henkaku.skprx is hard-coded to load and is not listed here
*main
ur0:tai/shellbat.suprx
ur0:tai/download_enabler.suprx
# main is a special titleid for SceShell
ur0:tai/henkaku.suprx
*NPXS10015
# this is for modifying the version string
ur0:tai/henkaku.suprx
*NPXS10016
# this is for modifying the version string in settings widget
ur0:tai/henkaku.suprx
#ux0:tai/vsh.suprx
*ALL
ur0:tai/VitaGrafix.suprx

**Comment by BaltazaR4** [comment]
Try deleting the adrenaline line under kernel at your config.txt, then launch adrenaline and make sure it loads the games, if everything works correctly then try launching one of the bubbles created with Adrenaline Bubbles Manager

**Comment by SaiyanFantasyX** [comment]
I've done it before. Games work fine in adrenaline. 
Also tried reinstalling both apps a couple times.

**Comment by ONElua** [comment]
You have adrenaline installed in sd2vita?

**Comment by SaiyanFantasyX** [comment]
I do, yeah. Both apps. Sd2vita is mounted as ux0.

**Comment by ONElua** [comment]
All you have to do is
- Edit your ur0:tai/config.txt file and delete the line under *KERNEL that says: ux0:adrenaline/adrenaline.skprx . and
ux0:app/PSPEMUCFW/sce_module/adrenaline_kernel.skprx
- delete any other line in config.txt that contains adrenaline.sprx
-make sure you don't have ux0:tai/config.txt or edit that one too if you have it. Note: I recommend only using ur0:tai/config.txt and getting rid of ux0:tai altogether, since ur0: has now been the default for a long time.
- delete your ux0:adrenaline folder
- delete your old adrenaline psp bubble (not needed with new Adrenaline)

reboot (this reboots your Vita system without loading the old adrenaline plugin)

install the new adrenaline.vpk
launch adrenaline and make sure it loads the games
install abm and make new bubbles

**Comment by SaiyanFantasyX** [comment]
The adrenaline folder you're mentioning is the one located in app, right? Well, if it is or not, I followed your steps and I'm still getting the same issue.

**Comment by ONElua** [comment]
do you have config in ux0:tai or uma0:tai ????
delete this config

**Comment by SaiyanFantasyX** [comment]
It's in ur0 only.

**Comment by SaiyanFantasyX** [comment]
Gonna try testing an older version of abm. Doubt it's gonna work, but I've ran out of ideas at this point.

**Comment by SaiyanFantasyX** [comment]
Fixed it by adding adrnubblebooter.suprx to config. 
Also rearanged it so that adrenaline_kernel amd adrbubblebooter are the next lines after *KERNEL.

I did run with an issue creating bubbles, though. 
If I selected 3 or more games, it would randomly crash the app. 5+ would always do it.
