### ISSUE TITLE
Make bubbles look identical to legit ones

### ISSUE THREAD

**Issue by azumukupoe** [ONElua/AdrenalineBubbleManager#30]

**Comment by BaltazaR4** [comment]
Well, I wonder if you mean to make them look like legit psp bubbles or legit ps vita game bubbles XD, but you can make them look like legit psp bubbles, in the main menu press R or L until the line "no stretched" shows below the selected game icon on the right upper corner, then you can change the bubble color by pressing right or left on the D-pad to change bubble color,  #15 will make your bubbles look like legit psp bubbles, as for the bubbles to look like ps vita game bubbles the icon will get stretched since the psp icons are rectangular and ps vita games icons are square.

**Comment by azumukupoe** [comment]
@BaltazaR4
I know those features, but they looked slightly different from legit ones. BTW, never mind.

**Comment by BaltazaR4** [comment]
I got you, if I remember well the icon is slightly bigger and the color around it is a bit lighter
