### ISSUE TITLE
Exiting a game with WLAN on crash next bubble

### ISSUE THREAD

**Issue by Catarax** [ONElua/AdrenalineBubbleManager#46]
When I exit a game with WLAN on (vita/pstv), the next bubble started will crash and will be require a reboot.

On games like Dragon Ball Z Shin Budokai 2, Tony hawk's Underground 2 Remix for example.

**Comment by BaltazaR4** [comment]
Double check how you have adrenaline setup, I mean if you have duplicated config.txt with the adrenaline lines or something else which could be conflicting with the Adrenaline plugins, the team tried with DBZ shin budokai 2 and some other games such as MHP 3rd, PE 3rd bday, MGS PW, KOF 95 withouth getting any issues at all, all of them with the ps vita wifi on, did not try on ps tv, do you have any plugins enabled for psp/psx? cause its not an Adrenaline Bubbles Manager issue.

**Comment by Catarax** [comment]
Thanks for checking!
Well if I do a proper PSP exit game to boot to VSH, I have no issue after exiting the bubble but when i'm directly using "Exit PSPEMU Application" while in game, the next game often go to a blackscreen.

Okay, tried to disable the psp plugins, no effects.

I have this config.txt in ux0 

```
*KERNEL
# henkaku.skprx is hard-coded to load and is not listed here
ux0:app/PSPEMUCFW/sce_module/adrenaline_kernel.skprx
ux0:tai/nonpdrm.skprx
*main
# main is a special titleid for SceShell
ur0:tai/henkaku.suprx
*NPXS10015
# this is for modifying the version string
ur0:tai/henkaku.suprx
*NPXS10016
# this is for modifying the version string in settings widget
ur0:tai/henkaku.suprx
```

and another in ur0.

**Comment by Catarax** [comment]
I notified I have no more blackscreen issue when using "exit to livearea" !

**Comment by ONElua** [comment]
> I have this config.txt in ux0

*KERNEL
# henkaku.skprx is hard-coded to load and is not listed here
ux0:app/PSPEMUCFW/sce_module/adrenaline_kernel.skprx
ux0:tai/nonpdrm.skprx
*main
# main is a special titleid for SceShell
ur0:tai/henkaku.suprx
*NPXS10015
# this is for modifying the version string
ur0:tai/henkaku.suprx
*NPXS10016
# this is for modifying the version string in settings widget
ur0:tai/henkaku.suprx

and another in ur0.> 
You only have to have one...
if you do not have sd2vita then use ux0:tai otherwise you must use ur0:tai
